### ISSUE TITLE
Crash on pack startup Fabric 1.20.1

### ISSUE THREAD

**Issue by Zykana** [sketchmacaw/MacawsDoors#4]
[crash-2023-07-19_12.49.06-client.txt](https://github.com/sketchmacaw/MacawsDoors/files/12098215/crash-2023-07-19_12.49.06-client.txt)

**Comment by sketchmacaw** [comment]
Do you have dramatic doors installed? If yes, just update it

**Comment by Zykana** [comment]
Yes this is now solved. Thank you.
